# Basic
tab_spaces = 2
hard_tabs = false
indent_style = "Visual"
max_width = 100
use_small_heuristics = "Max"
struct_lit_single_line = false
# Imports
imports_granularity = "Crate"
reorder_imports = true
imports_indent = "Visual"
# Consistency
newline_style = "Unix"
# Format comments
comment_width = 100
wrap_comments = true
# Misc
chain_width = 80
spaces_around_ranges = false
binop_separator = "Back"
reorder_impl_items = false
match_arm_leading_pipes = "Preserve"
match_arm_blocks = false
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
