@startuml composability
title "Fruniques Composability"
node "Statemine NFT A" as statemine_nft_a
node "Statemine NFT B" as statemine_nft_b

node "Frunique NFT 1" as frq_1
node "Frunique NFT 2" as frq_2
node "Frunique NFT n" as frq_n

node "Fungible Token" as fung_1
node "Frunique NFT 2.1" as frq_2_1
node "Frunique NFT 2.2" as frq_2_2
node "Frunique NFT 2.3" as frq_2_3

note left of frq_2
 Source NFT locked and 1..n new Fruniques 
 can be minted.
end note

note bottom of frq_2_1
 Metadata values are inherited by
 default unless overridden.
end note

note bottom of fung_1
 Parent Frunique owner decides 
 the token supply, symbol, and 
 metadata and is minted the tokens
end note

statemine_nft_a --> frq_1        
statemine_nft_b --> frq_2   
statemine_nft_b --> frq_n

frq_1 --> fung_1

frq_2 --> frq_2_1
frq_2 --> frq_2_2
frq_2 --> frq_2_3
@enduml