@startuml basket
title "Basket of Fungibles as Frunique"
node "75 MYCOINS" as statemine_fungible_a
node "29 DEFICOIN" as statemine_fungible_b
node "9 FRUN" as statemine_fungible_c
node "Statemine NFT C" as statemine_nft_c

node "Frunique NFT" as frq_2

note bottom of frq_2
 Can be further fractionalized via 
 fungible or non-fungibles
end note

note bottom of statemine_fungible_a
 Any set of tokens and/or NFTs can be 
 locked into a Frunique
end note

statemine_fungible_a --> frq_2        
statemine_fungible_b --> frq_2   
statemine_fungible_c --> frq_2
statemine_nft_c --> frq_2
@enduml