@startuml
node "Other Polkadot Ecosystem" as OPE {
  [Other Marketplaces]
}

package "Protocol Layer/Hashed Chain" {
  [Fruniques Pallet]
  [Marketplace Pallet] --> [Other Marketplaces]
  [Advanced Frunique UI/UX]
  [Services and Caching]
}

node "Statemint Chain" as SC {
  [Uniques Pallet]
  [Fruniques Pallet] --> [Uniques Pallet]
  [Fruniques Pallet] --> [Assets Pallet]
  [Assets Pallet]
  [Assets Pallet] --> [Other Marketplaces]
}

package "End User Experiences" {
  [Afloat/Tax Credits] --> [Fruniques Pallet]
  [Afloat/Tax Credits] --> [Services and Caching]
  [DAO LLC Registrations] --> [Fruniques Pallet]
  [DAO LLC Registrations] --> [Services and Caching]
  ['Get Gifted' NFTs] --> [Fruniques Pallet]
  [Marketplace UI/UX] --> [Fruniques Pallet]
  [Marketplace UI/UX] --> [Marketplace Pallet]
  ['Get Gifted' NFTs] --> [Marketplace UI/UX]
}
@enduml